#!/usr/bin/env bash

set -eu

package_name=$1
version=v3.20

alpine_mirror_site=${ALPINE_MIRROR_SITE-https://dl-cdn.alpinelinux.org}

url_x86_64=${alpine_mirror_site}/alpine/$version/main/x86_64/${package_name}
url_aarch64=${alpine_mirror_site}/alpine/$version/main/aarch64/${package_name}

wget -O /tmp/${package_name}.aarch64 $url_aarch64
wget -O /tmp/${package_name}.x86_64 $url_x86_64

sha_aarch64=$(sha256sum /tmp/${package_name}.aarch64 |awk '{print $1}')
echo "    - platform: aarch64-linux-musl"
echo "      url: $url_aarch64"
echo "      sha256: \"$sha_aarch64\""

sha_x86_64=$(sha256sum /tmp/${package_name}.x86_64 |awk '{print $1}')
echo "    - platform: x86_64-linux-musl"
echo "      url: $url_x86_64"
echo "      sha256: \"$sha_x86_64\""
