---
name: Build
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: restore cached downloads
        id: cache-download-restore
        uses: actions/cache/restore@v3
        with:
          path: downloads
          key: {{ runner.os }}-downloads

      - name: fetch all packages
        run: bundle exec rake fetch:all

      - name: generate package
        run: bundle exec rake package

      - name: archive actifacts
        uses: actions/upload-artifact@v3
        with:
          name: generated-package
          path: pkg/*.tar.xz
          retention-days: 5

      - name: save downloads in cache
        id: cache-download-sav
        uses: actions/cache/save@v3
        with:
          path: downloads
          key: ${{ steps.cache-download-restore.outputs.cache-primary-key }}
